# Generated by Django 4.2 on 2023-04-24 05:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='dob',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(1970)]),
        ),
    ]
