# Generated by Django 4.2 on 2023-04-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_alter_register_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='dob',
            field=models.DateField(max_length=50),
        ),
    ]
