# Generated by Django 4.2 on 2023-05-05 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_signin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignIn',
        ),
    ]
