# Generated by Django 4.2 on 2023-06-10 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_quesmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuesModel',
        ),
    ]
